server:
  port: "5001"

spring:
  jpa:
    generate-ddl: "true"
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
    properties:
      hibernate:
      dialect: "org.hibernate.dialect.PostgreSQL10Dialect"
  datasource:
    url: "jdbc:postgresql://db-cluster-ip-service:5432/sb_posts"
    username: "postgres"
    password: "Zxcv1234"
#  cloud:
#    stream:
#      bindings:
#        output:
#          destination: "postsChangeTopic"
#          content-type: "application/json"
#      kafka:
#        binder:
#          brokers: "kafka-cluster-ip-service"
  rabbitmq:
    host: rabbit-cluster-ip-service
    port: 5672


management:
  endpoints:
    web:
      exposure:
        include: "info, health"
