server:
  port: "5001"

spring:
  jpa:
    generate-ddl: "true"
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
#  cloud:
#    stream:
#      bindings:
#        output:
#          destination: "postsChangeTopic"
#          content-type: "application/json"
#      kafka:
#        binder:
#          brokers: "localhost"
  rabbitmq:
    host: localhost
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: "*"
