server:
  port: "5001"

spring:
  jpa:
    generate-ddl: "true"
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
    properties:
      hibernate:
      dialect: "org.hibernate.dialect.PostgreSQL10Dialect"
  datasource:
    url: "jdbc:postgresql://db-cluster-ip-service:5432/sb_posts"
    username: "postgres"
    password: "Zxcv1234"
  rabbitmq:
    host: rabbit-cluster-ip-service
    port: 5672

security:
  oauth2:
    resource:
      user-info-uri: http://auth-cluster-ip-service:5005/user/

my:
  event:
    queue: postsChangeEvent

management:
  endpoints:
    web:
      exposure:
        include: "info, health"
