server:
  port: "5001"

spring:
  jpa:
    generate-ddl: "true"
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
    properties:
      hibernate:
      dialect: "org.hibernate.dialect.PostgreSQL10Dialect"
  datasource:
    url: "jdbc:postgresql://db-cluster-ip-service:5432/sb_posts"
    username: "postgres"
    password: "Zxcv1234"

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.web: WARN
    org.springframework.data: DEBUG
    javax.persistence: DEBUG
    org.mike: DEBUG