server:
  port: "5001"

spring:
  jpa:
    generate-ddl: "true"
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
  rabbitmq:
    host: localhost
    port: 5672

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5005/user/
    client:
      grant-type: client_credentials

my:
  event:
    queue: postsChangeEvent

management:
  endpoints:
    web:
      exposure:
        include: "*"
