server:
  port: "5001"

spring:
  jpa:
    generate-ddl: "true"
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
    properties:
      hibernate:
      dialect: "org.hibernate.dialect.PostgreSQL10Dialect"
  datasource:
    url: "jdbc:postgresql://db.cfkmdc8gurae.eu-central-1.rds.amazonaws.com:5432/sb_posts"
    username: "postgres"
    password: "Zxcv1234"

management:
  endpoints:
    web:
      exposure:
        include: "*"