version: '3'
services:
  posts:
    image: mikebychkov/sb-posts
    mem_limit: 300000000
    ports:
      - "5001:5001"      
    environment:
      PROFILE: "doc"
      DB_SERVER: "db.cfkmdc8gurae.eu-central-1.rds.amazonaws.com:5432"
